#!/usr/bin/env bash

set -euo pipefail

SCRIPT="$HOME/.config/scripts/toggle-keyboard-layout"

layout=$(
    printf "qwerty\npine\ngallium\n" |
    rofi -dmenu \
         -i \
         -p "Keyboard Layout"
)

[[ -z "$layout" ]] && exit 0

"$SCRIPT" "$layout"
