#!/bin/sh

choice=$(printf " Lock\n Suspend\n Logout\n Reboot\n Poweroff" | rofi -dmenu -p "Power")

case "$choice" in
  " Lock") i3lock -c 000000 ;;
  " Logout") i3-msg exit ;;
  " Reboot") systemctl reboot ;;
  " Suspend") systemctl suspend ;;
  " Poweroff") systemctl poweroff ;;
esac

