# BEGIN_KITTY_THEME
# OneDark-Pro
include current-theme.conf
# END_KITTY_THEME

font_size 16.0
# font_family MesloLGM Nerd Font Mono


# BEGIN_KITTY_FONTS
font_family      family='MesloLGM Nerd Font Mono' postscript_name=MesloLGMNFM-Regular
# fallback for emojis
symbol_map U+1F300-U+1FAFF Noto Color Emoji
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

cursor_blink_interval 0.5
# 0 means never stop blinking
cursor_stop_blinking_after 0  
# cursor_shape beam
cursor_shape beam

# map alt+t new_tab
# map alt+w close_tab
# map f6 launch --location=vsplit
# map f5 launch --location=hsplit

map ctrl+shift+w no_op
