#!/usr/bin/env bash

killall -q polybar

while pgrep -u "$UID" -x polybar >/dev/null; do
    sleep 0.2
done

if command -v xrandr >/dev/null; then
    while read -r monitor; do
        MONITOR="$monitor" polybar --reload toph &
    done < <(xrandr --query | awk '/ connected/{print $1}')
else
    polybar --reload toph &
fi
