[ids]
*

[main]
capslock = layer(numbers)
rightalt = leftcontrol
escape = clearm(esc)

# --- Dvorak Remapping ---
# q = '
q = ;
w = ,
e = .
r = p
t = y
y = f
u = g
i = c
o = r
p = l
# [ = /
# ] = =

a = a
s = o
d = e
f = u
g = i
h = d
j = h
k = t
l = n
; = s
# ' = -

# z = /
x = q
c = j
v = k
b = x
n = b
m = m
, = w
. = v
# / = z

# - = [
# = = ]

[numbers]
; = oneshot(shift)
w = 1
e = 2
r = 3
t = 4
s = 5
d = 6
f = 7
g = 8
c = 9
v = 0
n = -
m = =
p = \
[ = `
b = toggle(shift)
x = oneshot(control)

i = backspace
o = delete
space = escape

h = left
j = down
k = up
l = right

y = home
u = end
