[colors]
bg-color              = #2f343f
inactive-bg-color     = #2f343f
inactive-border-color = #393e49
text-color            = #dbdcdd
inactive-text-color   = #676E7D
urgent-bg-color       = #E73F1E
border-color          = #595d65
focus-color           = #c2c3c4
underline-color       = #fab387
peach                 = #fab387

; Functional Polybar aliases
background            = ${colors.bg-color}
background-alt        = ${colors.inactive-border-color}
foreground            = ${colors.text-color}
primary               = ${colors.focus-color}
secondary             = ${colors.border-color}
alert                 = ${colors.urgent-bg-color}
disabled              = ${colors.inactive-text-color}
underline             = ${colors.underline-color}

[bar/toph]
monitor = ${env:MONITOR:}
width = 100%
height = 28pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

bottom = true
line-size = 3pt

border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = MesloLGS Nerd Font Mono:size=12;6
font-1 = MesloLGS Nerd Font Mono:size=15;6
font-2 = MesloLGS Nerd Font Mono:size=18;6
font-3 = MesloLGS Nerd Font Mono:size=22;6

modules-left = i3_workspace xwindow
modules-center = date
modules-right = pulseaudio battery-internal battery memory cpu wlan bluetooth

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
hidden = true

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt


[module/i3_workspace]
type = internal/i3
index-sort = true
wrapping-scroll = false

; Focused Workspace
label-focused = %name%
label-focused-background = ${colors.border-color}
label-focused-foreground = ${colors.foreground}
label-focused-underline  = ${colors.underline}
label-focused-padding    = 1

; Unfocused Workspace with open windows
label-unfocused = %name%
label-unfocused-background = ${colors.background}
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding    = 1

; Visible Workspace (active on a second monitor)
label-visible = %name%
label-visible-background = ${colors.background}
label-visible-foreground = ${colors.foreground}
label-visible-padding    = 1

; Urgent Workspace (Red alert highlight)
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-foreground = ${colors.foreground}
label-urgent-padding    = 1

; Empty Workspace
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding    = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:25:...%
label-foreground = ${colors.foreground}

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#6d7179}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false

format-volume = %{T3}<ramp-volume>%{T-} <label-volume>
label-volume = %percentage%%

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.primary}

label-muted = %{T3}%{T-} muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/battery]
type = internal/battery
format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}
full-at = 99
format-charging = <animation-charging> <label-charging>

animation-charging-0 = %{T3}%{T-}
animation-charging-1 = %{T3}%{T-}
animation-charging-2 = %{T3}%{T-}
animation-charging-3 = %{T3}%{T-}
animation-charging-4 = %{T3}%{T-}

animation-charging-framerate = 750
animation-charging-foreground = ${colors.peach}
format-discharging = <ramp-capacity> <label-discharging>

ramp-capacity-0 = %{T3}%{T-}
ramp-capacity-1 = %{T3}%{T-}
ramp-capacity-2 = %{T3}%{T-}
ramp-capacity-3 = %{T3}%{T-}
ramp-capacity-4 = %{T3}%{T-}

low-at = 5
battery = BAT1
adapter = ACAD
poll-interval = 5

[module/battery-internal]
type = internal/battery
format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}

full-at = 99
low-at = 5

battery = BAT0
adapter = ACAD
poll-interval = 5

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

animation-charging-0 = %{T3}%{T-}
animation-charging-1 = %{T3}%{T-}
animation-charging-2 = %{T3}%{T-}
animation-charging-3 = %{T3}%{T-}
animation-charging-4 = %{T3}%{T-}
animation-charging-framerate = 750
animation-charging-foreground = ${colors.peach}

ramp-capacity-0 = %{T3}%{T-}
ramp-capacity-1 = %{T3}%{T-}
ramp-capacity-2 = %{T3}%{T-}
ramp-capacity-3 = %{T3}%{T-}
ramp-capacity-4 = %{T3}%{T-}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#6d7179}%ifname%%{F#676E7D} disconnected

[module/wlan]
type = internal/network
interface = wlp3s0
interval = 5

format-connected = <label-connected>
label-connected = %{A1:kitty -e nmtui:}%{T2}%{T-} %essid%%{A}
label-connected-foreground = ${colors.primary}

format-disconnected = <label-disconnected>
label-disconnected = %{A1:kitty -e nmtui:}%{T2}%{T-} offline%{A}
label-disconnected-foreground = ${colors.disabled}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#6d7179}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %I:%M %p
date-alt = %A, %d %B %I:%M %p

label = %date%
label-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/bluetooth]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = kitty -e bluetoothctl

[module/lock]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = ~/.config/rofi/powermenu.sh

; vim:ft=dosini
